# -*- coding: utf-8 -*-

"""
/***************************************************************************
 smk_tools
                                 A QGIS plugin
 Suomen metsäkeskuksen työkalut
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-10-04
        copyright            : (C) 2022 by Suomen metsäkeskus
        email                : mikko.kesala@metsakeskus.fi
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Suomen metsäkeskus'
__date__ = '2022-10-04'
__copyright__ = '(C) 2022 by Suomen metsäkeskus'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'
from stat import S_ISLNK
from qgis import processing
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication,QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterDefinition,
                       QgsProcessingUtils)
import os,time,sys
sys.path.append(os.path.dirname(__file__))
from PIL import Image
from saastopuu import *
pluginPath = os.path.abspath(
    os.path.join(
        os.path.dirname(__file__),
        os.pardir))

class saastopuu_toolsAlgorithm(QgsProcessingAlgorithm):


    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    FOSFORI = 'FOSFORI'
    DTW = 'DTW'
    BIOD = 'BIOD'
    LAHOP = 'LAHOP'
    PUUM = 'PUUM'
    INPUT = 'INPUT'

    standfields = ['SPECIALFEATURECODE','SPECIALFEATUREADDITIONALCODE']
    gfields = ['FERTILITYCLASS','DEVELOPMENTCLASS','STEMCOUNTPINE','STEMCOUNTDECIDUOUS','STEMCOUNTSPRUCE','MEANDIAMETERDECIDUOUS','MEANDIAMETERPINE','MEANDIAMETERSPRUCE','MEANHEIGHTDECIDUOUS','MEANHEIGHTPINE','MEANHEIGHTSPRUCE']


    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Leimikko'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )
        params = []

        params.append(
            QgsProcessingParameterEnum(
                self.FOSFORI,
                self.tr('Ravinteiden pidättyminen'),
                options=['Ei painotusta','Pieni','Keskimääräinen','Suuri'],
                defaultValue=1
            )
            )

        params.append(
            QgsProcessingParameterEnum(
                self.DTW,
                self.tr('Maaperän kosteus'),
                options=['Ei painotusta','Pieni','Keskimääräinen','Suuri'],
                defaultValue=1
            )
            )

        params.append(
            QgsProcessingParameterEnum(
                self.BIOD,
                self.tr('Puuston monimuotoisuus'),
                options=['Ei painotusta','Pieni','Keskimääräinen','Suuri'],
                defaultValue=1
            )
            )

        params.append(
            QgsProcessingParameterEnum(
                self.LAHOP,
                self.tr('Lahopuupotentiaali'),
                options=['Ei painotusta','Pieni','Keskimääräinen','Suuri'],
                defaultValue=1
            )
            )
        

        for p in params:
            p.setFlags(p.flags() | QgsProcessingParameterDefinition.FlagAdvanced) 
            self.addParameter(p)

        self.addParameter(
            QgsProcessingParameterNumber(
                self.PUUM,
                self.tr('Säästöpuiden määrä (kpl /ha)'),
                type=QgsProcessingParameterNumber.Integer,
                minValue=5,maxValue=30,defaultValue=10
            )
            )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Säästöpuut')
            )
        )
    

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        feedb = {1:feedback.pushInfo,
                2:feedback.pushWarning,
                3:feedback.reportError}
        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        if source.featureCount() > 20:
            feedback.reportError("Input layer has too many features. 20 features is maximum. Process failed.")
            sys.exit()

        #feedback.pushInfo(str(parameters['INPUT']))
        source = processing.run("native:dissolve", {'INPUT':parameters['INPUT'],'FIELD':[],'OUTPUT':'TEMPORARY_OUTPUT'})
        source = processing.run("native:multiparttosingleparts", {'INPUT':source['OUTPUT'],'OUTPUT':'TEMPORARY_OUTPUT'})
        source = source['OUTPUT']
       
        
        # Compute the number of steps to display within the progress bar and
        #slayer = QgsVectorLayer(parameters['INPUT'],"slayer","ogr")
        # get features from source
        
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        
        features = source.getFeatures()
        for current, feature in enumerate(features):
            #feedback.setProgressText("testia ja "+str(out))
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break
            
            #out.select(feature.id())
            #uri = "polygon?crs="+str(source.sourceCrs())+"&field=id:integer&"
            #QgsVectorLayer(uri,"mem","memory")
            feedback.setProgressText("Haetaan aineistot rajapinnasta")

            #leimFeat = feature.getFeatures()
            leimArea = [feature.geometry().area()/10000]
            out = feature2Layer(feature,100)
            out1 = feature2Layer(feature,0)
            out.setCrs(source.crs())
            out1.setCrs(source.crs())

            chm = getRaster(out)
            feedb[chm[2]](chm[1])
            
            stand = getFeatureFromWfs(out,'stand')
            feedb[stand[2]](stand[1])

            fgrid = getFeatureFromWfs(out,'gridcell')
            feedb[fgrid[2]](fgrid[1])

            dtw = getDTW(out,"dtw")
            feedb[dtw[2]](dtw[1])

            biogeo = geom2esri(out)
            euc = getDTW(out,"euc")
            feedb[euc[2]](euc[1])
            
            proSites = getProtectedSites(out)
            leim = handleInput(out1)
            #joinList = [stand,fgrid,biogeo,proSites]
            #print (proSites)
            #if proSites is not None
            feedback.setProgress(10)

            
            feedback.setProgressText("Aloitetaan puukartan luonti")
            feedback.setProgress(10)
            #print (chm)
            chm =processRaster(chm[0])
            feedback.setProgress(20)
            feedback.setProgressText("vektoroidaan puukartta")
            feedback.setProgress(30)
            
            outChm = vectorCHM(chm)

            feedback.setProgress(40)

            feedback.setProgressText("Rikastetaan tiedot")
            feedback.setProgress(50)


            outChm = joinForestData(outChm,stand[0],self.standfields)
            outChm = joinForestData(outChm,fgrid[0],self.gfields)
            outChm = joinForestData(outChm,biogeo,[])
            outChm = joinForestData(outChm,proSites,[])
            outChm = joinForestData(outChm,leim,['leimikko'])

            if dtw[2]==1:
                outChm = processing.run("native:rastersampling", {'INPUT':outChm,'RASTERCOPY':dtw[0],'COLUMN_PREFIX':'DTW_','OUTPUT':'TEMPORARY_OUTPUT'})
                outChm = outChm['OUTPUT']
            else:
                outChm.dataProvider().addAttributes([QgsField("DTW_1",QVariant.Double)])
                outChm.updateFields()
                
            if euc[2]==1:
                outChm = processing.run("native:rastersampling", {'INPUT':outChm,'RASTERCOPY':euc[0],'COLUMN_PREFIX':'euc_','OUTPUT':'TEMPORARY_OUTPUT'})
                outChm = outChm['OUTPUT']
            else:
                outChm.dataProvider().addAttributes([QgsField("euc_1",QVariant.Double)])
                outChm.updateFields()

            feedback.setProgressText("Lasketaan ympäristötekijöiden arvot")
            feedback.setProgress(60)
            
            
            normalizeValue(outChm,'DTW_1')
            normalizeValue(outChm,'euc_1')
            
            calculateDecayTreePotential(outChm)
            calculateBiodiversity(outChm)
            
            calculateNPretention(outChm)

            feedback.setProgress(70)

            fosf = self.parameterAsInt(parameters,self.FOSFORI,context)
            dtw = self.parameterAsInt(parameters,self.DTW,context)
            biod = self.parameterAsInt(parameters,self.BIOD,context)
            lahop = self.parameterAsInt(parameters,self.LAHOP,context)
            weights ={"NP":float(fosf),"BIO":float(biod),"LP":float(lahop),"DTW":float(dtw)}
            puuMaara = self.parameterAsInt(parameters,self.PUUM,context)
            
            calculateEnvValue(outChm,weights)
            outChm = hsAnalysis(outChm,'env_value')

            feedback.setProgressText("koko: "+str(round(leimArea[0],2))+"\ns-puiden määrä: "+str(int(puuMaara*leimArea[0])))
            
            out = optimizeRetentioTrees(outChm['OUTPUT'],leimArea[0],puuMaara)
            
            idx=[]
            idx.append(out.fields().indexFromName('fid'))
            idx.append(out.fields().indexFromName('OBJECTID'))
            out.dataProvider().deleteAttributes(idx)
            out.updateFields()

            #self.informText.setText("Säästöpuugraafi: "+t)
            feedback.setProgressText("viimeistellään")

            for i in range(70,100):
                time.sleep(0.004)
                feedback.setProgress(i+1)

            style = os.path.join(os.path.dirname(__file__),"reTree3.qml")
           
       
            #out = outChm['OUTPUT']
            # Add a feature in the sink
            if current == 0:
                (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,context,
                    out.fields(), out.wkbType(), out.crs())
            #feedback.pushInfo(str(out.fields().names()))
            outFeats = out.getFeatures()
            for outFeat in outFeats:
                #feedback.pushInfo(str(outFeat['CHM']))
                sink.addFeature(outFeat, QgsFeatureSink.FastInsert)
        
            layer = QgsProcessingUtils.mapLayerFromString(dest_id, context)
        
            if str((layer.dataProvider().dataSourceUri())).startswith("memory?") == True:
                graafi = ""
            else:
                filefold = os.path.dirname(layer.dataProvider().dataSourceUri())
                feedback.pushInfo(str(filefold))
                graafi = os.path.join(filefold,"Ympäristötekijät.png")
        
            #feedback.pushInfo("test: "+str(te))
            graafi = makeRetentionGraph(out,graafi)
            g = Image.open(graafi)
            g.show()
            #sink.setName("Säästöpuut")
            

        

            # Update the progress bar
            feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        layer.loadNamedStyle(style)
        return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Luo säästöpuuehdotus'

    def icon(self):
        
        return QIcon(os.path.join(pluginPath, 'icon.jpg'))

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'SMK luontotieto'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return saastopuu_toolsAlgorithm()
